services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-net
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    networks:
      - mongo-net
    depends_on:
      - mongodb

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    networks:
      - mongo-net
    command: "python main.py"

networks:
  mongo-net:

volumes:
  mongodb_data_container:
